### ISSUE TITLE
Car search timing out

### ISSUE THREAD

**Issue by Monika-Mistry** [Monika-Mistry/Twyndyllyngs#56]
Searching a car by a number plate results in the folllowing error:
![TimeOut](https://user-images.githubusercontent.com/22007575/63844775-b0293c00-c980-11e9-8638-a9e5742e951d.PNG)

docker-compose login logs:
```POST /getCarDetails/ - - ms - -
Executing (default): SELECT `id`, `username`, `password`, `usertype`, `createdAt`, `updatedAt` FROM `users` AS `users` WHERE `users`.`id` = 2;
Unhandled rejection ReferenceError: Headers is not defined
    at getCarRequest (/usr/src/app/scenario/carSearch.js:11:47)
    at passport.authenticate (/usr/src/app/scenario/carSearch.js:29:13)
    at JwtStrategy.strategy.success (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:214:18)
    at verified (/usr/src/app/node_modules/passport-jwt/lib/strategy.js:115:41)
    at User.findOne.then.user (/usr/src/app/config/passport.js:105:21)
    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/usr/src/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by biomiller** [comment]
removed references to Header from carSearch.js
